In [1]:
import numpy as np
## https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/

# Create Empty Array

In [2]:

empArry = np.empty(4,dtype=int)
empArry

array([ 1169457113, -1347963513,  1381176688,  1020568799])

In [3]:
empArry = np.empty((2,3),dtype=int, order='F')
empArry

array([[  182744720,           0,      131074],
       [        425,           0, -1929288702]])

In [4]:
empArry = np.empty((2,3),dtype=int, order='C')
empArry

array([[182744720,       425,         0],
       [        0,    131074, 542978336]])

In [5]:
empArry = np.empty((2,3),dtype=float)
empArry

array([[0., 0., 0.],
       [0., 0., 0.]])

# Full Array

In [6]:
fullArry = np.full(4,10,dtype=float)
fullArry

array([10., 10., 10., 10.])

In [7]:
fullArry = np.full((4,5),10,dtype=float)
fullArry

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [8]:
fullArry = np.full(4,10,dtype=int,order='F')
fullArry

array([10, 10, 10, 10])

In [9]:
fullArry = np.full([4,2],60,dtype=int,order='F')
fullArry

array([[60, 60],
       [60, 60],
       [60, 60],
       [60, 60]])

# Zero Matrix/Array

In [10]:
zeroMar = np.zeros((4,2))
zeroMar

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
zeroMar = np.zeros((4,2),dtype=int)
zeroMar

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [12]:
zeroMar = np.zeros(2)
zeroMar

array([0., 0.])

# One Matrix/Array

In [13]:
oneMar = np.ones(3)
oneMar

array([1., 1., 1.])

# Check whether a Numpy array contains a specified row

In [15]:
ar = np.array([2,3,4])
ar1 = np.array(["Abc","tt"])
ar2 = np.array([[1,2,3],[5,6,7],[9,8,7]])

In [22]:
print(2 in ar.tolist())
print("Abc" in ar1.tolist())
print("abc" in ar1.tolist())
print([1,5,6] in ar2.tolist())
print([5,6,7] in ar2.tolist())
print([7,8,9] in ar2.tolist())

True
True
False
False
True
False


# Remove rows in Numpy array that contains non-numeric values

In [20]:
list1 = [54.6,67.89,34.6,5]
list2 = [45,np.nan,98,np.nan]
ar = np.array([list1,list2])
print("Given Array " , ar )
print(ar[~np.isnan(ar).any(axis=1)])

Given Array  [[54.6  67.89 34.6   5.  ]
 [45.     nan 98.     nan]]
[[54.6  67.89 34.6   5.  ]]


# number of occurrences of a sequence

In [26]:
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
op = repr(arr).count("9")
print(op)

5


# most frequent value in a NumPy array

In [42]:
x = np.array([1,2,5,9,5,6,8,9,5,1,1,4,2,6,8,5])
print(np.bincount(x))
print(np.bincount(x).argmax())
print(np.bincount(x).argmax(axis=0))
print("-------------")
x1 = np.array([11,21,31,31,41,51,51,11])
a = np.bincount(x1)
print("Count Of Each Unique Elements" , a)
maxi = max(a)
print("Maximum Count ",maxi)
for i in range(len(a)):
    if a[i] == maxi:
        print(i)

[0 3 2 0 1 4 2 0 2 2]
5
5
-------------
Count Of Each Unique Elements [0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 2]
Maximum Count  2
11
31
51


# Combining a one and a two-dimensional NumPy Array

In [6]:
n1d = np.arange(5)
print("One Dim",n1d)
n2d = np.arange(10).reshape(2,5)
print("Two Dim",n2d)
for i , j in np.nditer([n1d,n2d]):
    print(i , ":",j)
listd = []     
for i , j in np.nditer([n1d,n2d]):
    listd.append(i*j) 
print(np.array(listd).reshape(2,5))

One Dim [0 1 2 3 4]
Two Dim [[0 1 2 3 4]
 [5 6 7 8 9]]
0 : 0
1 : 1
2 : 2
3 : 3
4 : 4
0 : 5
1 : 6
2 : 7
3 : 8
4 : 9
[[ 0  1  4  9 16]
 [ 0  6 14 24 36]]


# build an array of all combinations of two NumPy arrays

In [16]:
arr1 = np.array([1,2])
arr2 = np.array([3,4,5])
comb_arr = np.array(np.meshgrid(arr1,arr2))
print(comb_arr)
print("==============")
print(comb_arr.T.reshape(-1,2))

[[[1 2]
  [1 2]
  [1 2]]

 [[3 3]
  [4 4]
  [5 5]]]
[[1 3]
 [1 4]
 [1 5]
 [2 3]
 [2 4]
 [2 5]]


# Add a border around a NumPy array 


In [25]:
arr1 = np.zeros((2,2),dtype=int)
print("Given" , arr1)
op = np.pad(arr1,pad_width=1,constant_values=5)
print("================")
print(op)
op = np.pad(arr1,pad_width=3,constant_values=5)
print("================")
print(op)

Given [[0 0]
 [0 0]]
[[5 5 5 5]
 [5 0 0 5]
 [5 0 0 5]
 [5 5 5 5]]
[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 0 0 5 5 5]
 [5 5 5 0 0 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


# Compare two NumPy arrays

In [28]:
aa1 = np.array([[1,2],[3,4]])
aa2 = np.array([[1,2],[3,4]])
aa3 = np.array([[1,2],[5,4]])
compare = aa1 == aa2
print(compare)
print(compare.all())
print("==========")
compare = aa1 == aa3
print(compare.all())

[[ True  True]
 [ True  True]]
True
False


In [39]:
a = np.arange(5,dtype=int)
b = np.arange(3,8,dtype=int)
print("Given Aray :" ,a , b)
print("a > b" , np.greater(a , b))
print("a >= b" , np.greater_equal(a , b))
print("a < b" , np.less(a , b))
print("a <= b" , np.less_equal(a , b))

Given Aray : [0 1 2 3 4] [3 4 5 6 7]
a > b [False False False False False]
a >= b [False False False False False]
a < b [ True  True  True  True  True]
a <= b [ True  True  True  True  True]


# check whether specified values are present 

In [41]:
a = np.array([1,2,3,4])
print(6 in a)
print(2 in a)

False
True


# 2D diagonals of a 3D NumPy array

In [46]:
arr = np.arange(3 * 4 * 4).reshape(3 , 4 , 4)
print(arr)
dia = np.diagonal(arr , axis1=1,axis2=2)
print(dia)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
[[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]


# Flatten a Matrix

In [63]:
ord = np.arange(5,9).reshape(2,2)
print(ord)
f1 = ord.flatten()
print(f1)
f2 = ord.flatten(order = 'F')
print(f2)
f3 = ord.flatten(order='A')
print(f3)
f3 = ord.flatten(order='K')
print(f3)

[[5 6]
 [7 8]]
[5 6 7 8]
[5 7 6 8]
[5 6 7 8]
[5 6 7 8]


In [65]:
ord = np.arange(6).reshape(3,2)
print(ord)
f2 = ord.flatten(order = 'F')
print(f2)
f3 = ord.flatten(order='A')
print(f3)

[[0 1]
 [2 3]
 [4 5]]
[0 2 4 1 3 5]
[0 1 2 3 4 5]


In [66]:
ord = np.arange(6).reshape(3,2)
print(ord)
print(ord.ravel())

[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


# Move axis

In [79]:
arr = np.array([1,2,3,4,5])
print(arr)
print(np.moveaxis(arr,0,-1).shape)

[1 2 3 4 5]
(5,)


# Trim Zeros

In [97]:
arr = np.array((0,3,560,0,7,8,9,0,0))
arr1 = np.array([[0,21,5,65,2],[0,6,9,0,0]])
print(arr1)
re = np.trim_zeros(arr)
print(re)
re = np.trim_zeros(arr1.flatten())
print(re)

[[ 0 21  5 65  2]
 [ 0  6  9  0  0]]
[  3 560   0   7   8   9]
[21  5 65  2  0  6  9]


# Change Type of Element

In [104]:
arr = np.array([52,36,63])
print(arr.dtype)
print(arr)
arr = arr.astype("float64")
print(arr.dtype)
print(arr)

int32
[52 36 63]
float64
[52. 36. 63.]


# Reverse a numpy array

In [106]:
arr = np.arange(5)
print(arr)
print(arr[::-1])

[0 1 2 3 4]
[4 3 2 1 0]


# Change the array to readable

In [108]:
arr = np.arange(5)
print(arr)
arr[1]=2
print(arr)
arr.flags.writable =False
arr[1]=3

[0 1 2 3 4]
[0 2 2 3 4]


AttributeError: 'numpy.flagsobj' object has no attribute 'writable'